-- MySQL Script generated by MySQL Workbench
-- Mon Aug 28 07:43:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema residencialesdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `residencialesdb` ;

-- -----------------------------------------------------
-- Schema residencialesdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `residencialesdb` DEFAULT CHARACTER SET utf8 ;
USE `residencialesdb` ;

-- -----------------------------------------------------
-- Table `residencialesdb`.`residential`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `residencialesdb`.`residential` (
  `idresidential` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(200) NULL,
  `phone` VARCHAR(9) NULL,
  `email` VARCHAR(100) NULL,
  `nit` VARCHAR(15) NULL,
  `logo` VARCHAR(400) NULL,
  `status` INT NOT NULL,
  `create_time` DATETIME NULL,
  `create_user` INT NULL,
  `modify_time` DATETIME NULL,
  `modify_user` INT NULL,
  PRIMARY KEY (`idresidential`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `residencialesdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `residencialesdb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(16) NULL,
  `password` VARCHAR(256) NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(9) NOT NULL,
  `code` VARCHAR(45) NULL,
  `address` VARCHAR(100) NULL,
  `position` VARCHAR(100) NULL,
  `photo` VARCHAR(400) NULL,
  `employee` INT NULL,
  `status` INT NOT NULL,
  `idresidential` INT NOT NULL,
  `create_time` DATETIME NULL,
  `create_user` INT NULL,
  `modify_time` DATETIME NULL,
  `modify_user` INT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_user_residential1_idx` (`idresidential` ASC) VISIBLE,
  CONSTRAINT `fk_user_residential1`
    FOREIGN KEY (`idresidential`)
    REFERENCES `residencialesdb`.`residential` (`idresidential`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `residencialesdb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `residencialesdb`.`role` (
  `idrole` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `status` INT NOT NULL,
  `create_time` DATETIME NULL,
  `create_user` INT NULL,
  `modify_time` DATETIME NULL,
  `modify_user` INT NULL,
  PRIMARY KEY (`idrole`));


-- -----------------------------------------------------
-- Table `residencialesdb`.`role_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `residencialesdb`.`role_user` (
  `iduser` INT NOT NULL,
  `idrole` INT NOT NULL,
  INDEX `fk_rol_user_user_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_rol_user_rol1_idx` (`idrole` ASC) VISIBLE,
  PRIMARY KEY (`iduser`, `idrole`),
  CONSTRAINT `fk_rol_user_user`
    FOREIGN KEY (`iduser`)
    REFERENCES `residencialesdb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol_user_rol1`
    FOREIGN KEY (`idrole`)
    REFERENCES `residencialesdb`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `residencialesdb`.`page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `residencialesdb`.`page` (
  `idpage` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idpage`),
  UNIQUE INDEX `name_UNIQUE` (`path` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `residencialesdb`.`role_page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `residencialesdb`.`role_page` (
  `idrole` INT NOT NULL,
  `idpage` INT NOT NULL,
  INDEX `fk_category_role1_idx` (`idrole` ASC) VISIBLE,
  INDEX `fk_category_role_page1_idx` (`idpage` ASC) VISIBLE,
  CONSTRAINT `fk_category_role1`
    FOREIGN KEY (`idrole`)
    REFERENCES `residencialesdb`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_role_page1`
    FOREIGN KEY (`idpage`)
    REFERENCES `residencialesdb`.`page` (`idpage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `residencialesdb`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `residencialesdb`.`service` (
  `idservice` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `description` VARCHAR(100) NULL,
  `idresidential` INT NOT NULL,
  `status` INT NULL,
  `create_time` DATETIME NULL,
  `create_user` INT NULL,
  `modify_time` DATETIME NULL,
  `modify_user` INT NULL,
  PRIMARY KEY (`idservice`),
  INDEX `fk_service_residential1_idx` (`idresidential` ASC) VISIBLE,
  CONSTRAINT `fk_service_residential1`
    FOREIGN KEY (`idresidential`)
    REFERENCES `residencialesdb`.`residential` (`idresidential`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `residencialesdb`.`ticket_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `residencialesdb`.`ticket_type` (
  `idtype` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idtype`));


-- -----------------------------------------------------
-- Table `residencialesdb`.`ticket_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `residencialesdb`.`ticket_status` (
  `idstatus` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idstatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `residencialesdb`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `residencialesdb`.`ticket` (
  `idticket` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(100) NULL,
  `description` VARCHAR(400) NOT NULL,
  `creation_date` DATETIME NULL,
  `iduser` INT NOT NULL,
  `idticket_type` INT NOT NULL,
  `idstatus` INT NOT NULL,
  `idresidential` INT NOT NULL,
  PRIMARY KEY (`idticket`),
  INDEX `fk_ticket_user1_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_ticket_ticket_type1_idx` (`idticket_type` ASC) VISIBLE,
  INDEX `fk_ticket_ticket_status1_idx` (`idstatus` ASC) VISIBLE,
  INDEX `fk_ticket_residential1_idx` (`idresidential` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `residencialesdb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_ticket_type1`
    FOREIGN KEY (`idticket_type`)
    REFERENCES `residencialesdb`.`ticket_type` (`idtype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_ticket_status1`
    FOREIGN KEY (`idstatus`)
    REFERENCES `residencialesdb`.`ticket_status` (`idstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_residential1`
    FOREIGN KEY (`idresidential`)
    REFERENCES `residencialesdb`.`residential` (`idresidential`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `residencialesdb`.`service_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `residencialesdb`.`service_request` (
  `idservicerequest` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(200) NOT NULL,
  `iduser` INT NULL,
  `idresidential` INT NOT NULL,
  `status` INT NULL,
  `idservice` INT NOT NULL,
  `create_time` DATETIME NULL,
  `create_user` INT NULL,
  `modify_time` DATETIME NULL,
  `modify_user` INT NULL,
  PRIMARY KEY (`idservicerequest`),
  INDEX `fk_service_user1_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_service_residential1_idx` (`idresidential` ASC) VISIBLE,
  INDEX `fk_service_request_service1_idx` (`idservice` ASC) VISIBLE,
  CONSTRAINT `fk_service_user10`
    FOREIGN KEY (`iduser`)
    REFERENCES `residencialesdb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_residential10`
    FOREIGN KEY (`idresidential`)
    REFERENCES `residencialesdb`.`residential` (`idresidential`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_request_service1`
    FOREIGN KEY (`idservice`)
    REFERENCES `residencialesdb`.`service` (`idservice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `residencialesdb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `residencialesdb`.`comment` (
  `idcomment` INT NOT NULL AUTO_INCREMENT,
  `ticket_idticket` INT NOT NULL,
  `user_id` INT NOT NULL,
  `attachment` VARCHAR(200) NULL,
  `date` DATETIME NULL,
  `commentcol` VARCHAR(45) NULL,
  INDEX `fk_comment_ticket1_idx` (`ticket_idticket` ASC) VISIBLE,
  INDEX `fk_comment_user1_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`idcomment`),
  CONSTRAINT `fk_comment_ticket1`
    FOREIGN KEY (`ticket_idticket`)
    REFERENCES `residencialesdb`.`ticket` (`idticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `residencialesdb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `residencialesdb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `residencialesdb`.`message` (
  `idmessage` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `start_date` DATETIME NULL,
  `final_date` DATETIME NULL,
  `idresidential` INT NOT NULL,
  `idstatus` INT NOT NULL,
  `iduser` INT NULL,
  `attachment` VARCHAR(100) NULL,
  `type` VARCHAR(1) NULL,
  `create_time` DATETIME NULL,
  `create_user` INT NULL,
  `modify_time` DATETIME NULL,
  `modify_user` INT NULL,
  INDEX `fk_message_residential1_idx` (`idresidential` ASC) VISIBLE,
  INDEX `fk_message_ticket_status1_idx` (`idstatus` ASC) VISIBLE,
  INDEX `fk_message_user1_idx` (`iduser` ASC) VISIBLE,
  PRIMARY KEY (`idmessage`),
  CONSTRAINT `fk_message_residential1`
    FOREIGN KEY (`idresidential`)
    REFERENCES `residencialesdb`.`residential` (`idresidential`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_ticket_status1`
    FOREIGN KEY (`idstatus`)
    REFERENCES `residencialesdb`.`ticket_status` (`idstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `residencialesdb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- INSERTS
-- -----------------------------------------------------
INSERT INTO residential (name,address,phone,email,nit,logo,status,create_time,create_user,modify_time,modify_user) VALUES
	 ('DS','guatemala','12345678','cesar970@gmail.com','','',1,NOW(),1,NULL,NULL),
	 ('demo1','guatemala','12345678','cesar970@gmail.com','','',1,NOW(),1,NULL,NULL);

INSERT INTO `user` (name,username,password,email,phone,code,address,`position`,photo,employee,status,create_time,create_user,modify_time,modify_user,idresidential) VALUES
	 ('Cesar Joel Bojorquez','cesar','','cesar970@gmail.com','','','gau','','',1,1,NOW(),1,NULL,NULL,1),
	 ('Juan ','','','cesar970@gmail.com','30391123','','villa nueva','Jardinero','',0,1,NOW(),1,NULL,NULL,1),
	 ('miguel','','','cesar970@gmail.com','30391123',NULL,'villa nueva',NULL,'',0,1,NOW(),1,NULL,NULL,2);

INSERT INTO `residencialesdb`.`role` (`name`, `status`, `create_time`, `create_user`) VALUES ('ROLE_ADMIN', '1', NOW(), '1');

INSERT INTO `residencialesdb`.`ticket_type` (`name`) VALUES ('Gestion');
INSERT INTO `residencialesdb`.`ticket_type` (`name`) VALUES ('Anomalia');

INSERT INTO `residencialesdb`.`ticket_status` (`description`) VALUES ('Creado');
INSERT INTO `residencialesdb`.`ticket_status` (`description`) VALUES ('Abierto');
INSERT INTO `residencialesdb`.`ticket_status` (`description`) VALUES ('En progreso');
INSERT INTO `residencialesdb`.`ticket_status` (`description`) VALUES ('Cerrado');
